# Generated by Django 5.1.4 on 2025-03-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='work_location',
            field=models.CharField(choices=[('Workshop', 'Workshop'), ('Syspal', 'Syspal')], default='Workshop', max_length=15),
        ),
    ]
